### ISSUE TITLE
Spark 3.2 no longer support ?

### ISSUE THREAD

**Issue by MyqueWooMiddo** [apache/sedona#1813]
spark 3.2.2 + sedona 1.7.0 

when reading shapefile  via 
val df = sedona.read.format("shapefile").load("hdfs:///user/spark/shp/");
df.show

It throwed :
java.lang.NoSuchMethodError: org.apache.sedona.sql.datasources.shapefile.ShapefileScanBuilder.pushedDataFilters()[Lorg/apache/spark/sql/sources/Filter;
  at org.apache.sedona.sql.datasources.shapefile.ShapefileScanBuilder.build(ShapefileScanBuilder.scala:44)
  at org.apache.spark.sql.execution.datasources.v2.PushDownUtils$.pruneColumns(PushDownUtils.scala:133)

Cause :
when spark >= 3.3.0
org.apache.spark.sql.execution.datasources.v2.FileScanBuilder contains "pushedDataFilters" property

**Comment by jiayuasu** [comment]
yes, we dropped the support of Spark 3.2 in Sedona 1.7.0

**Comment by MrPowers** [comment]
Spark 3.2 is supported in Sedona 1.6.1 though: https://sedona.apache.org/1.6.1/setup/platform/

So you can just use an older version of Sedona and it will work with Spark 3.2 perfectly!
